config/routes.rb
Rails.application.routes.draw do
  resources :products
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products	
end

app/models/product.rb
class Product < ActiveRecord::Base
	extend Enumerize

	belongs_to :category

	validates :title, :description, presence: true
	validates :price, :numericality => { :greater_than => 0}, presence: true
	validate :must_have_category

	before_validation :strip_html_from_description, :set_title_to_lowcase

	scope :published, -> {where(published: true)}
	scope :priced_more_than, ->(price) {where('price > ?', price)}

	def strip_html_from_description
	  self.description = ActionView::Base.full_sanitizer.sanitize(self.description)	
	end

	def set_title_to_lowcase
	  self.title = self.title.downcase	
	end

	def must_have_category
      if category.blank?
        self.errors.add(:category, "not existence") 
      end
    end

    enumerize :difficulty_level, in: [:hard, :medium, :easy]
    enumerize :country_origin, in: Country.all.map{|country_value, country_code|  country_code}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
		@products = Product.all.includes(:category).published
	end

	def show
		@product = Product.find(params[:id])
	end

	def new
	  @product = Product.new	
	end
  
  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      # Handle a successful update.
    else
      render 'edit'
    end
  end

	def create
	  @product = Product.new(product_params)	
	  if @product.save
      flash[:notice] = "you have successfully created product"
	    redirect_to products_url
	  else
      flash.now[:notice] = "there is an error in your form"
	  	render :new  
	  end
	end
  
  def destroy
    @product = Product.find(params[:id]).destroy
    flash[:success] = "Product deleted"
    redirect_to products_url
  end
  
	private 
	  def product_params
	  	params.require(:product).permit(:title, :description, :price, :category_id)
	  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Railsfun</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |name, msg|%>
  <%= content_tag :div, msg, class: name %>
<% end %>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= semantic_form_for @product do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :price, min: 0.01 %>
  <%= f.input :published %>
  <%= f.input :category %>
  <%= f.action :submit %>
<% end %>

app/views/products/_product.html.erb
<tr>
  <td><%= link_to product.category.title, product_path(product) %></td>                   
  <td><%= product.price %><td>
  <td><%= link_to 'Delete', product_path(product), method: :delete, data: {confirm: 'Are you sure u want to delete this product?'} %></td>                   
</tr>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<table style="width:100%, border='1'">
  <tr>
    <td>Category</td>
    <td>Price</td>
  </tr>
  <tr>
<% @products.each do |product| %> 
<tr>
  <%= render :partial => 'product', locals: {product: product} %>                 
</tr>
<% end %>
</table

app/views/products/new.html.erb
<%= semantic_form_for @product do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :price, min: 0.01 %>
  <%= f.input :published %>
  <%= f.input :category %>
  <%= f.action :submit %>
<% end %>

app/views/products/show.html.erb
<dl>
<dt> Title
	<dd><%=@product.title%></dd>
</dt>
<dt> Price
	<dd><%=@product.description%></dd>
</dt>
<dt> Description
	<dd><%=@product.price%></dd>
</dt>
</dl>